"use client";
import { useEffect, useState } from "react";
import { Agent, Application, Assignment, Booking, Market, Message, OrderEvent, Unavailable, api, Area, buttonClass, Field, formValues, inputClass, Panel } from "./shared";
type Data = { applications: Application[]; agents: Agent[]; markets: Market[]; bookings: Booking[]; assignments: Assignment[]; events: OrderEvent[]; messages: Message[]; unavailable: Unavailable[] };
function Territories({ markets, selected = [] }: { markets: Market[]; selected?: string[] }) {
  return <fieldset className="space-y-2"><legend className="font-medium text-sm mb-2">Assigned countries and cities</legend><div className="grid gap-2 sm:grid-cols-2">{markets.map(m => <label key={m.id} className="flex gap-2 text-sm"><input type="checkbox" name="marketIds" value={m.id} defaultChecked={selected.includes(m.id)} />{m.country_code} · {m.name}</label>)}</div></fieldset>;
}
export default function AdminAgents() {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [credentials, setCredentials] = useState<{ email: string; password: string } | null>(null), [application, setApplication] = useState<Application | null>(null), [tab, setTab] = useState("Applications");
  async function load() { try { setData(await api("/api/admin/agents")); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { api("/api/admin/agents").then(setData).catch(e => setError(e.message)); }, []);
  async function save(body: Record<string, unknown>) {
    setBusy(true); setError(""); setNotice("");
    try {
      const result = await api("/api/admin/agents", body);
      if (result.password) setCredentials({ email: String(body.email || data?.agents.find(a => a.id === body.id)?.email || ""), password: result.password });
      setNotice("Saved successfully."); await load(); return true;
    } catch (e) { setError((e as Error).message); return false; } finally { setBusy(false); }
  }
  return <div className="space-y-6 max-w-6xl"><header><h1 className="text-3xl font-bold text-white">Agent Management</h1><p className="mt-2 text-neutral-400">Review applications, manage city coverage, and assign orders to local partners.</p></header>
    {error && <p role="alert" className="rounded-lg bg-red-100 p-4 text-red-900">{error}</p>}{notice && <p role="status" className="text-teal-300">{notice}</p>}
    {credentials && <Panel title="Account credentials — shown only now"><p>Share these directly with the agent through a trusted channel. They must change the password at first login.</p><p>Login: <a className="underline" href="/agent/login">https://rentandroll.com/agent/login</a></p><p>Email: {credentials.email}</p><code className="block break-all rounded bg-neutral-100 p-3 select-all">{credentials.password}</code><button type="button" className={buttonClass} onClick={() => setCredentials(null)}>I have saved the credentials</button></Panel>}
    {data && <div className="grid grid-cols-2 xl:grid-cols-4 gap-3">{[["New applications", data.applications.filter(a => a.status === "new").length], ["Active agents", data.agents.filter(a => a.is_active).length], ["Orders needing assignment", data.bookings.filter(b => !data.assignments.some(a => a.booking_id === b.id && a.status !== "declined")).length], ["Offers awaiting acceptance", data.assignments.filter(a => a.status === "offered" && data.bookings.some(b => b.id === a.booking_id)).length]].map(([label, count]) => <div key={label} className="rounded-xl bg-neutral-900 border border-neutral-800 p-4"><b className="text-2xl text-teal-300">{count}</b><p className="text-sm text-neutral-400 mt-1">{label}</p></div>)}</div>}
    <nav aria-label="Agent management sections" className="flex flex-wrap gap-2">{["Applications", "Agents", "Orders", "Availability", "Cities", "Activity"].map(t => <button key={t} onClick={() => setTab(t)} className={`rounded-lg px-4 py-2 ${tab === t ? "bg-teal-600 text-white" : "bg-neutral-800 text-neutral-300"}`}>{t}{t === "Applications" && data ? ` (${data.applications.filter(a => a.status === "new").length} new)` : ""}</button>)}</nav>
    {!data ? <p className="text-neutral-300">Loading agent management…</p> : <>
      {tab === "Applications" && <div className="space-y-4"><p className="text-neutral-400">Latest 500 applications. Approval and account creation are separate actions so you can agree on operating terms first.</p>{data.applications.length === 0 && <Panel title="No applications yet"><a className="text-teal-700 underline" href="/agent-network">Open the recruitment page</a></Panel>}{data.applications.map(a => <Panel key={a.id} title={`${a.full_name} · ${a.city}, ${a.country_code}`}><p className="text-sm">{a.email} · {a.phone} · {new Date(a.created_at).toLocaleDateString()}</p><dl className="grid gap-2 text-sm"><div><b>Business:</b> {a.business_name || "—"}</div><div><b>Service area:</b> {a.area_of_operations}</div><div><b>Experience:</b> {a.experience || "—"}</div><div><b>Equipment:</b> {a.equipment || "—"}</div></dl><form className="space-y-3" onSubmit={e => { const values = formValues(e); void save({ ...values, action: "application", id: a.id }); }}><label className="block text-sm">Status<select name="status" defaultValue={a.status} className={inputClass}>{["new", "reviewing", "approved", "rejected"].map(s => <option key={s}>{s}</option>)}</select></label><Area name="admin_notes" label="Private review notes" value={a.admin_notes} /><div className="flex gap-3"><button disabled={busy} className={buttonClass}>Save review</button>{!data.agents.some(agent => agent.agent_territories && agent.email === a.email) && <button type="button" className="underline text-teal-700" onClick={() => { setApplication(a); setTab("Agents"); }}>Create agent from application</button>}</div></form></Panel>)}</div>}
      {tab === "Agents" && <div className="space-y-5"><Panel title="Create agent account"><form key={application?.id || "new"} className="space-y-4" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget, values = new FormData(form); if (await save({ action: "create", full_name: values.get("full_name"), email: values.get("email"), marketIds: values.getAll("marketIds"), applicationId: application?.id })) { setApplication(null); form.reset(); } }}><div className="grid gap-4 sm:grid-cols-2"><Field name="full_name" label="Full name" value={application?.full_name} /><Field name="email" type="email" label="Login email" value={application?.email} /></div>{application && <p className="text-sm">Linked to {application.full_name}&apos;s application. <button type="button" className="underline" onClick={() => setApplication(null)}>Clear</button></p>}<Territories markets={data.markets} /><p className="text-sm text-neutral-500">A strong temporary password is generated automatically. Verify the email address and agree on responsibilities before sharing access.</p><button className={buttonClass} disabled={busy}>Create account and generate password</button></form></Panel>{data.agents.map(a => <Panel key={a.id} title={`${a.full_name} · ${a.is_active ? "Active" : "Suspended"}`}><p>{a.email} · {a.must_change_password ? "Password change required" : a.profile_completed_at ? "Onboarding complete" : "Profile incomplete"}</p><details><summary className="cursor-pointer text-teal-700">Contact and operational profile</summary><div className="mt-3 space-y-1 text-sm"><p>{a.phone} · {a.contact_email}</p><p>{a.business_name} · {a.address}</p><p>Area: {a.area_of_operations || "Not completed"}</p><p>Languages: {a.languages}</p><p>Availability: {a.availability_notes}</p></div></details><form className="space-y-4" onSubmit={e => { e.preventDefault(); void save({ action: "territories", id: a.id, marketIds: new FormData(e.currentTarget).getAll("marketIds") }); }}><Territories markets={data.markets} selected={a.agent_territories?.map(t => t.market_id)} /><button className={buttonClass} disabled={busy}>Save coverage</button></form><div className="flex flex-wrap gap-4 text-sm"><button disabled={busy} className="underline" onClick={() => { if (confirm(`${a.is_active ? "Suspend" : "Reactivate"} ${a.full_name}? Existing sessions will be ended.`)) void save({ action: "active", id: a.id, is_active: !a.is_active }); }}>{a.is_active ? "Suspend access" : "Reactivate access"}</button><button disabled={busy} className="underline" onClick={() => { if (confirm(`Reset the password for ${a.full_name}? Existing sessions will be ended.`)) void save({ action: "reset", id: a.id }); }}>Generate replacement password</button></div></Panel>)}</div>}
      {tab === "Orders" && <div className="space-y-4"><p className="text-neutral-400">Open paid orders (up to 500), ordered by rental start. Reassignment removes the previous agent&apos;s access and closes their customer reply link.</p>{!data.bookings.length && <Panel title="No open paid orders"><p>Paid bookings appear here for assignment.</p></Panel>}{data.bookings.map(b => { const assignment = data.assignments.find(a => a.booking_id === b.id); return <Panel key={b.id} title={`${b.booking_ref} · ${b.products?.name || "Rental"}`}><p>{b.start_date} → {b.end_date} · {b.customer_name} · {b.status}</p><p className="text-sm">{data.markets.find(m => m.id === b.market_id)?.name} · Current assignment: {assignment ? `${data.agents.find(a => a.id === assignment.agent_id)?.full_name} (${assignment.status})` : "Unassigned"}{assignment?.decline_reason && ` — ${assignment.decline_reason}`}</p><form className="flex flex-wrap gap-3" onSubmit={e => { const values = formValues(e); if (!assignment || confirm("Replace the current assignment and reset its schedule?")) void save({ action: "assign", bookingId: b.id, agentId: values.agentId }); }}><label className="flex-1 min-w-48"><span className="sr-only">Assign agent</span><select name="agentId" required className={inputClass} defaultValue=""><option value="">Choose agent in this city</option>{data.agents.filter(a => a.is_active && a.agent_territories?.some(t => t.market_id === b.market_id)).map(a => <option key={a.id} value={a.id} disabled={data.unavailable.some(u => u.agent_id === a.id && u.start_date <= b.end_date && u.end_date >= b.start_date)}>{a.full_name}{data.unavailable.some(u => u.agent_id === a.id && u.start_date <= b.end_date && u.end_date >= b.start_date) ? " (unavailable for these dates)" : ""}</option>)}</select></label><button className={buttonClass} disabled={busy}>Assign order</button></form></Panel>; })}</div>}
      {tab === "Availability" && <Panel title="Agent unavailable dates"><p>These periods prevent overlapping assignments across all of the agent&apos;s cities. Agents manage dates in their Calendar; existing orders must be reassigned first.</p>{data.unavailable.length ? data.unavailable.map(u => <div key={u.id} className="border-t py-3"><b>{data.agents.find(a => a.id === u.agent_id)?.full_name}</b><p>{u.start_date} ? {u.end_date}</p><p className="text-sm text-neutral-500">{u.reason || "No additional note"}</p></div>) : <p className="text-neutral-500">No unavailable periods recorded.</p>}</Panel>}
      {tab === "Cities" && <Panel title="Add an operational city"><p>City coverage prepares the agent network. Adding a city here does not enable public bookings, pricing or inventory in that city.</p><form className="grid gap-4 sm:grid-cols-2" onSubmit={e => { const values = formValues(e); void save({ ...values, action: "market" }); }}><Field name="name" label="City name" maxLength={100} /><Field name="slug" label="Unique identifier (e.g. madrid)" maxLength={80} /><Field name="country_code" label="Country code (e.g. ES)" maxLength={2} /><Field name="timezone" label="Time zone (e.g. Europe/Madrid)" maxLength={100} /><Field name="currency" label="Currency code (e.g. EUR)" maxLength={3} /><button disabled={busy} className={buttonClass}>Add city</button></form><ul className="divide-y">{data.markets.map(m => <li className="py-2" key={m.id}>{m.country_code} · {m.name} · {m.timezone} · {m.is_booking_enabled ? "Booking enabled" : "Network preparation"}</li>)}</ul></Panel>}
      {tab === "Activity" && <div className="grid gap-5 lg:grid-cols-2"><Panel title="Latest order activity"><p className="text-sm text-neutral-500">Latest 200 events. Internal notes are visible here for operational follow-up.</p>{data.events.map(e => <div key={e.id} className="border-t pt-3 text-sm"><p className="font-medium">{data.agents.find(a => a.id === e.agent_id)?.full_name} · {e.action}</p><p>Order {data.bookings.find(b => b.id === e.booking_id)?.booking_ref || e.booking_id}</p><p className="whitespace-pre-wrap">{e.note}</p><time>{new Date(e.created_at).toLocaleString()}</time></div>)}</Panel><Panel title="Customer communication"><p className="text-sm text-neutral-500">Latest 200 messages. Failed messages remain visible for follow-up.</p>{data.messages.map(m => <div key={m.id} className="border-t pt-3 text-sm"><p className="font-medium">{m.direction === "customer" ? "Customer" : data.agents.find(a => a.id === m.agent_id)?.full_name} · {m.status}</p><p>Order {data.bookings.find(b => b.id === m.booking_id)?.booking_ref || m.booking_id}</p><p className="whitespace-pre-wrap">{m.body}</p><time>{new Date(m.created_at).toLocaleString()}</time></div>)}</Panel></div>}
    </>}
  </div>;
}
