"use client";
import { useState } from "react";
import { dateInZone, monthDays, shiftMonth } from "@/lib/agent-workspace";
import { Workspace, Panel, Field, buttonClass, formValues, inputClass } from "./shared";
import { getStops, stopTime } from "./operations";
export default function AgentCalendar({ data, busy, save, openOrder }: { data: Workspace; busy: boolean; save: (body: Record<string, unknown>) => Promise<boolean>; openOrder: (id: string) => void }) {
  const today = dateInZone(new Date(), data.territories[0]?.markets.timezone);
  const [month, setMonth] = useState(today.slice(0, 7)), [selected, setSelected] = useState(today), [city, setCity] = useState("");
  const stops = getStops(data).filter(s => !city || s.order.bookings.market_id === city);
  const selectedStops = stops.filter(s => s.date === selected);
  return <div className="space-y-6"><Panel title="Delivery calendar"><div className="flex flex-wrap justify-between gap-3"><div className="flex items-center gap-3"><button aria-label="Previous month" className="border rounded-lg px-3 py-2" onClick={() => setMonth(shiftMonth(month, -1))}>←</button><h3 className="font-semibold">{new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}-01T12:00:00Z`))}</h3><button aria-label="Next month" className="border rounded-lg px-3 py-2" onClick={() => setMonth(shiftMonth(month, 1))}>→</button><button className="text-teal-700 underline" onClick={() => { setMonth(today.slice(0, 7)); setSelected(today); }}>Today</button></div><label><span className="sr-only">Calendar city</span><select className={inputClass} value={city} onChange={e => setCity(e.target.value)}><option value="">All assigned cities</option>{data.territories.map(t => <option value={t.market_id} key={t.market_id}>{t.markets.country_code} · {t.markets.name}</option>)}</select></label></div>
    <div className="grid grid-cols-7 text-center text-xs sm:text-sm">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(d => <div className="py-3 font-medium text-neutral-500" key={d}>{d}</div>)}{monthDays(month).map(day => {
      const count = stops.filter(s => s.date === day).length, unavailable = data.unavailable.some(u => u.start_date <= day && u.end_date >= day);
      return <button key={day} onClick={() => setSelected(day)} aria-label={`${day}, ${count} stops${unavailable ? ", unavailable" : ""}`} aria-pressed={selected === day} className={`min-h-20 sm:min-h-24 border p-1 sm:p-2 text-left ${selected === day ? "bg-teal-100 border-teal-600" : unavailable ? "bg-amber-50" : "bg-white hover:bg-neutral-50"} ${day.slice(0, 7) !== month ? "text-neutral-400" : "text-neutral-900"}`}><span className={`inline-flex w-6 h-6 items-center justify-center rounded-full ${day === today ? "bg-teal-800 text-white" : ""}`}>{Number(day.slice(-2))}</span>{count > 0 && <span className="block text-xs text-teal-800 mt-1">{count} {count === 1 ? "stop" : "stops"}</span>}{unavailable && <span className="block text-[10px] sm:text-xs text-amber-800">Away</span>}</button>;
    })}</div><p className="text-xs text-neutral-500">Only remaining delivery and collection stops are shown. Dates and times use each city&apos;s time zone; unscheduled stops use rental dates.</p></Panel>
    <Panel title={`Agenda · ${selected}`}>{selectedStops.length ? selectedStops.map(s => <button key={s.order.booking_id + s.kind} onClick={() => openOrder(s.order.booking_id)} className="w-full text-left border-t py-4 flex flex-wrap gap-3 justify-between"><span><b className="capitalize">{s.kind}</b> · {s.order.bookings.booking_ref}<span className="block text-sm text-neutral-600">{s.order.bookings.products?.name} · {s.order.bookings.customer_name}</span><span className="block text-sm">{s.market?.name} · {s.driver?.name || "Unassigned / self"}</span></span><span className="text-sm text-teal-800">{stopTime(s)}<span className="block text-xs">{s.market?.timezone}</span></span></button>) : <p className="text-neutral-500">No stops for this date and city selection.</p>}</Panel>
    <Panel title="Your unavailable dates"><p className="text-sm text-neutral-600">Block dates when you cannot take new assignments in any of your cities. Existing overlapping orders must be declined or reassigned first. This does not change customer bookings or catalogue stock.</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={async e => { const form = e.currentTarget, values = formValues(e); if (await save({ action: "availability", ...values })) form.reset(); }}><Field name="start_date" label="First unavailable day" type="date" /><Field name="end_date" label="Last unavailable day (inclusive)" type="date" /><Field name="reason" label="Note for admin (optional)" required={false} maxLength={500} /><button disabled={busy} className={buttonClass}>Block dates</button></form>{data.unavailable.map(u => <div key={u.id} className="border-t py-3 flex justify-between gap-4"><div><b>{u.start_date} → {u.end_date}</b><p className="text-sm text-neutral-600">{u.reason}</p></div><button disabled={busy} className="text-teal-700 underline" onClick={() => { if (confirm("Remove this unavailable period? New orders may be assigned on these dates.")) void save({ action: "availability", id: u.id }); }}>Remove</button></div>)}{!data.unavailable.length && <p className="text-sm text-neutral-500">No unavailable dates recorded.</p>}</Panel></div>;
}
