"use client";
import { useEffect, useState } from "react";
import AgentProfile from "./AgentProfile";
import AgentOrder from "./AgentOrder";
import { Agent, Assignment, Driver, Market, Message, OrderEvent, api, buttonClass, Field, formValues, inputClass, Panel } from "./shared";
type Workspace = { agent: Agent; territories: { market_id: string; markets: Market }[]; orders: Assignment[]; drivers: Driver[]; messages: Message[]; events: OrderEvent[] };
export default function AgentWorkspace() {
  const [data, setData] = useState<Workspace | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [tab, setTab] = useState("Orders"), [filter, setFilter] = useState("open"), [search, setSearch] = useState("");
  async function load() {
    const response = await fetch("/api/agent/workspace", { cache: "no-store" });
    if (response.status === 401) { window.location.replace("/agent/login"); return; }
    const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result);
  }
  useEffect(() => { fetch("/api/agent/workspace", { cache: "no-store" }).then(async response => {
    if (response.status === 401) { window.location.replace("/agent/login"); return; }
    const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result);
  }).catch(e => setError(e.message)); }, []);
  async function send(path: string, body: Record<string, unknown>, method = "POST") {
    setBusy(true); setError(""); setNotice(""); let success = false;
    try { const result = await api(path, body, method); setNotice(result.warning || "Saved successfully."); success = true; }
    catch (e) { setError((e as Error).message); }
    try { await load(); } catch (e) { setError((e as Error).message); }
    setBusy(false); return success;
  }
  const open = (o: Assignment) => ["paid", "delivering", "active", "returning"].includes(o.bookings.status);
  const ready = data && !data.agent.must_change_password && !!data.agent.profile_completed_at;
  const orders = data?.orders.filter(o => (filter === "all" || (filter === "open" ? open(o) && o.status !== "declined" : o.status === filter)) && `${o.bookings.booking_ref} ${o.bookings.products?.name || ""} ${o.bookings.customer_name || ""}`.toLowerCase().includes(search.toLowerCase())) || [];
  const manifest = data?.orders.filter(o => o.status === "accepted" && open(o)).flatMap(o => (["delivery", "collection"] as const).map(kind => {
    const market = data.territories.find(t => t.market_id === o.bookings.market_id)?.markets;
    const scheduled = kind === "delivery" ? o.delivery_scheduled_at : o.collection_scheduled_at;
    const driver = data.drivers.find(d => d.id === (kind === "delivery" ? o.delivery_driver_id : o.collection_driver_id));
    return { order: o, kind, market, scheduled, driver };
  })).sort((a, b) => (a.scheduled || "9999").localeCompare(b.scheduled || "9999")) || [];
  return <div className="container-site py-10 space-y-6"><header className="flex flex-wrap items-start justify-between gap-4 print:hidden"><div><h1 className="text-3xl font-bold">Agent workspace</h1><p className="mt-2 text-neutral-600">{data?.agent.full_name || "Your local operations"}</p></div><div className="flex gap-4"><button className="text-teal-700 underline" disabled={busy} onClick={() => void load().catch(e => setError(e.message))}>Refresh</button><button className="underline" onClick={async () => { try { await api("/api/agent/session", undefined, "DELETE"); window.location.replace("/agent/login"); } catch (e) { setError((e as Error).message); } }}>Sign out</button></div></header>
    {error && <p role="alert" className="bg-red-50 text-red-800 p-4 rounded-lg">{error}</p>}{notice && <p role="status" className="text-teal-700 print:hidden">{notice}</p>}
    {!data ? <p>Loading your workspace…</p> : <><p className="text-sm text-neutral-500 print:hidden">Assigned coverage: {data.territories.map(t => `${t.markets.country_code} · ${t.markets.name}`).join(" / ") || "Awaiting assignment"}</p>
      {!ready && <div className="bg-amber-50 text-amber-900 rounded-lg p-4">Complete both onboarding steps below to unlock your assigned orders and customer details.</div>}
      {ready && <><div className="grid gap-3 sm:grid-cols-4 print:hidden">{[["New assignments", data.orders.filter(o => open(o) && o.status === "offered").length], ["Accepted open orders", data.orders.filter(o => open(o) && o.status === "accepted").length], ["Completed orders", data.orders.filter(o => o.bookings.status === "completed" && o.status === "accepted").length], ["Customer replies", data.messages.filter(m => m.direction === "customer").length]].map(([label, count]) => <div key={label} className="rounded-xl border p-4"><p className="text-2xl font-bold text-teal-700">{count}</p><p className="text-sm">{label}</p></div>)}</div><nav aria-label="Agent workspace sections" className="flex flex-wrap gap-2 print:hidden">{["Orders", "Manifest", "Drivers", "Profile"].map(t => <button onClick={() => setTab(t)} key={t} className={tab === t ? buttonClass : "rounded-lg border px-4 py-2"}>{t}</button>)}</nav></>}
      {(!ready || tab === "Profile") && <AgentProfile agent={data.agent} busy={busy} save={body => send("/api/agent/workspace", body)} changePassword={body => send("/api/agent/session", body, "PATCH")} />}
      {ready && tab === "Orders" && <><div className="flex flex-wrap gap-3"><label className="flex-1"><span className="sr-only">Search orders</span><input value={search} onChange={e => setSearch(e.target.value)} className={inputClass} placeholder="Search reference, product or customer" /></label><label><span className="sr-only">Filter orders</span><select className={inputClass} value={filter} onChange={e => setFilter(e.target.value)}><option value="open">Open orders</option><option value="offered">New assignments</option><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="all">All recent orders</option></select></label></div><p className="text-sm text-neutral-500">Up to 300 recent assigned orders. Refresh to receive new assignments and customer replies.</p><div className="space-y-5">{orders.length ? orders.map(o => <AgentOrder key={`${o.booking_id}-${o.status}`} order={o} market={data.territories.find(t => t.market_id === o.bookings.market_id)?.markets} drivers={data.drivers} messages={data.messages.filter(m => m.booking_id === o.booking_id)} events={data.events.filter(e => e.booking_id === o.booking_id)} busy={busy} act={body => send("/api/agent/orders", body)} />) : <Panel title="No matching orders"><p>The admin assigns orders in your approved cities. New assignments will appear here.</p></Panel>}</div></>}
      {ready && tab === "Manifest" && <Panel title="Delivery and collection manifest"><p>Accepted open orders. Times use the city&apos;s time zone. Unscheduled stops appear last.</p><button className={`${buttonClass} print:hidden`} onClick={() => window.print()}>Print manifest</button><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Stop / order", "Time / city", "Customer", "Address / instructions", "Driver"].map(h => <th key={h} className="p-3 border-b">{h}</th>)}</tr></thead><tbody>{manifest.map(({ order: o, kind, market, scheduled, driver }) => <tr key={`${o.booking_id}-${kind}`} className="align-top"><td className="p-3 border-b"><b>{kind}</b><br />{o.bookings.booking_ref}<br />{o.bookings.products?.name} × {o.bookings.quantity}<br />{o.bookings.status}</td><td className="p-3 border-b">{scheduled ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: market?.timezone || "UTC" }).format(new Date(scheduled)) : "Not scheduled"}<br />{market?.name}<br />{market?.timezone}</td><td className="p-3 border-b">{o.bookings.customer_name}<br />{o.bookings.customer_phone}</td><td className="p-3 border-b whitespace-pre-wrap">{kind === "delivery" ? o.bookings.delivery_address : o.bookings.collection_address || o.bookings.delivery_address}<br />{kind === "delivery" ? o.bookings.delivery_notes : o.bookings.collection_notes}</td><td className="p-3 border-b">{driver?.name || "Unassigned / self"}<br />{driver?.phone}<br />{driver?.vehicle}</td></tr>)}</tbody></table></div>{!manifest.length && <p>No accepted open orders.</p>}</Panel>}
      {ready && tab === "Drivers" && <div className="space-y-5"><Panel title="Add a driver"><p>Drivers are contact records for your own operations; they do not receive workspace accounts.</p><form className="grid gap-4 sm:grid-cols-2" onSubmit={async e => { const form = e.currentTarget, values = formValues(e); if (await send("/api/agent/workspace", { ...values, action: "driver" })) form.reset(); }}><Field name="name" label="Driver name" /><Field name="phone" label="Phone" type="tel" maxLength={50} /><Field name="vehicle" label="Vehicle / registration (optional)" required={false} /><button className={buttonClass} disabled={busy}>Add driver</button></form></Panel>{data.drivers.map(d => <Panel title={d.name} key={d.id}><form className="grid gap-4 sm:grid-cols-2" onSubmit={e => { const values = formValues(e); void send("/api/agent/workspace", { ...values, action: "driver", id: d.id, is_active: values.is_active === "on" }); }}><Field name="name" label="Name" value={d.name} /><Field name="phone" label="Phone" value={d.phone} type="tel" maxLength={50} /><Field name="vehicle" label="Vehicle" value={d.vehicle} required={false} /><label className="flex items-center gap-3"><input name="is_active" type="checkbox" defaultChecked={d.is_active} />Active driver</label><button disabled={busy} className={buttonClass}>Save driver</button></form></Panel>)}</div>}
    </>}
  </div>;
}
