"use client";
import { useState } from "react";
import { Assignment, Driver, Market, Message, OrderEvent, Area, buttonClass, Field, formValues, inputClass, Panel } from "./shared";
const nextStatus: Record<string, string> = { paid: "delivering", delivering: "active", active: "returning", returning: "completed" };
const statusLabel: Record<string, string> = { delivering: "Start delivery / handover", active: "Confirm delivered / handed over", returning: "Start collection / return", completed: "Confirm collected / returned" };
function localDate(iso: string | null) {
  if (!iso) return "";
  const date = new Date(iso); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
}
export default function AgentOrder({ order, market, drivers, messages, events, busy, act }: { order: Assignment; market?: Market; drivers: Driver[]; messages: Message[]; events: OrderEvent[]; busy: boolean; act: (body: Record<string, unknown>) => Promise<boolean> }) {
  const b = order.bookings, open = ["paid", "delivering", "active", "returning"].includes(b.status);
  const [messageId, setMessageId] = useState<string | null>(null);
  const run = (body: Record<string, unknown>) => act({ ...body, bookingId: b.id });
  return <Panel title={`${b.booking_ref} · ${b.products?.name || "Rental"}`}><p>{b.quantity} item(s) · {b.start_date} → {b.end_date} · {market?.name}, {market?.country_code}</p><p className="font-medium text-teal-800">{order.status} · {b.status} · {b.fulfillment_mode?.replaceAll("_", " ")}</p>
    {order.status === "offered" && open && <div className="space-y-3"><p>Accept only if you can fulfill the rental dates and coordinate delivery or handover. Customer details appear after acceptance.</p><button className={buttonClass} disabled={busy} onClick={() => void run({ action: "accept" })}>Accept assignment</button><form className="flex gap-3" onSubmit={e => { const values = formValues(e); void run({ action: "decline", ...values }); }}><label className="flex-1"><span className="sr-only">Reason for declining</span><input className={inputClass} name="note" required minLength={3} maxLength={2000} placeholder="Reason for declining" /></label><button disabled={busy} className="underline">Decline</button></form></div>}
    {order.status === "declined" && <p>Reason: {order.decline_reason}</p>}
    {order.status === "accepted" && <><div className="rounded-lg bg-neutral-50 p-4 space-y-2"><p className="font-semibold">{b.customer_name}</p><p>{b.customer_phone} · {b.customer_email}</p><p><b>Delivery:</b> {b.delivery_address || "See handover instructions"}</p><p className="whitespace-pre-wrap">{b.delivery_notes}</p><p><b>Collection:</b> {b.collection_address || b.delivery_address || "See return instructions"}</p><p className="whitespace-pre-wrap">{b.collection_notes}</p></div>
      {open && <div className="space-y-4">{b.requires_confirmation && b.confirmation_status !== "approved" ? <p className="text-amber-800">Admin confirmation is required before progressing this order.</p> : <button disabled={busy} className={buttonClass} onClick={() => { if (confirm(`${statusLabel[nextStatus[b.status]]}? This updates the order's operational status.`)) void run({ action: "status", status: nextStatus[b.status] }); }}>{statusLabel[nextStatus[b.status]]}</button>}
        <details><summary className="cursor-pointer font-medium text-teal-700">Delivery and collection schedule</summary><form className="mt-4 space-y-4" onSubmit={e => { const values = formValues(e); void run({ ...values, action: "schedule", deliveryAt: values.deliveryAt ? new Date(String(values.deliveryAt)).toISOString() : "", collectionAt: values.collectionAt ? new Date(String(values.collectionAt)).toISOString() : "" }); }}><p className="text-sm">Enter times in your device time zone ({Intl.DateTimeFormat().resolvedOptions().timeZone}). The manifest displays {market?.timezone || "the city time zone"}. Agree changes with the customer; this does not change rental dates.</p><div className="grid gap-3 sm:grid-cols-2"><Field name="deliveryAt" type="datetime-local" label="Delivery / handover time" value={localDate(order.delivery_scheduled_at)} required={false} /><Field name="collectionAt" type="datetime-local" label="Collection / return time" value={localDate(order.collection_scheduled_at)} required={false} />{["delivery", "collection"].map(kind => <label key={kind} className="text-sm">{kind === "delivery" ? "Delivery driver" : "Collection driver"}<select className={inputClass} name={`${kind}DriverId`} defaultValue={(kind === "delivery" ? order.delivery_driver_id : order.collection_driver_id) || ""}><option value="">Unassigned / self</option>{drivers.filter(d => d.is_active || d.id === order.delivery_driver_id || d.id === order.collection_driver_id).map(d => <option key={d.id} value={d.id} disabled={!d.is_active}>{d.name}{!d.is_active ? " (inactive)" : ""}</option>)}</select></label>)}</div><button disabled={busy} className={buttonClass}>Save schedule</button></form></details>
        <form className="space-y-3" onSubmit={async e => { const form = e.currentTarget, values = formValues(e); if (await run({ ...values, action: "note" })) form.reset(); }}><Area name="note" label="Internal note / issue for admin (not sent to customer)" required /><button disabled={busy} className={buttonClass}>Save operational note</button></form>
      </div>}
      <details><summary className="cursor-pointer font-medium text-teal-700">Customer conversation ({messages.length})</summary><div className="space-y-3 mt-4">{messages.slice().reverse().map(m => <div key={m.id} className={`rounded-lg p-3 ${m.direction === "customer" ? "bg-teal-50" : "bg-neutral-50"}`}><p className="text-xs font-semibold">{m.direction === "customer" ? "Customer" : "You"} · {m.status} · {new Date(m.created_at).toLocaleString()}</p><p className="whitespace-pre-wrap mt-1">{m.body}</p>{open && m.direction === "agent" && ["failed", "queued"].includes(m.status) && <button className="underline text-teal-700" disabled={busy} onClick={() => void run({ action: "message", messageId: m.id, body: m.body })}>Retry email</button>}</div>)}{open && <form className="space-y-3" onSubmit={async e => { const form = e.currentTarget, values = formValues(e), id = messageId || crypto.randomUUID(); setMessageId(id); if (await run({ action: "message", body: values.body, messageId: id })) { form.reset(); } setMessageId(null); }}><Area name="body" label="Message to customer" required /><p className="text-sm text-neutral-500">Sends an email to the booking customer with a private reply link. Replies appear here; use Refresh to check for new messages.</p><button className={buttonClass} disabled={busy}>Send customer message</button></form>}</div></details>
      <details><summary className="cursor-pointer text-teal-700">Order history</summary>{events.map(e => <div className="border-t py-2 text-sm" key={e.id}>{new Date(e.created_at).toLocaleString()} · {e.action}<p className="whitespace-pre-wrap">{e.note}</p></div>)}</details>
    </>}
  </Panel>;
}
