"use client";
import { useState } from "react";
import { Workspace, buttonClass, Field, formValues, inputClass, Panel } from "./shared";
import { getStops, stopTime } from "./operations";
export function AgentManifest({ data, openOrder }: { data: Workspace; openOrder: (id: string) => void }) {
  const [date, setDate] = useState(""), [driverId, setDriverId] = useState(""), [city, setCity] = useState("");
  const stops = getStops(data).filter(s => (!date || s.date === date) && (!driverId || (driverId === "unassigned" ? !s.driver : s.driver?.id === driverId)) && (!city || s.market?.id === city));
  return <div className="agent-print-manifest"><Panel title="Delivery & collection manifest"><div className="flex flex-wrap gap-3 print:hidden"><label className="text-sm">Date<input type="date" className={inputClass} value={date} onChange={e => setDate(e.target.value)} /></label><label className="text-sm">Driver<select className={inputClass} value={driverId} onChange={e => setDriverId(e.target.value)}><option value="">All drivers</option><option value="unassigned">Unassigned / self</option>{data.drivers.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-sm">City<select className={inputClass} value={city} onChange={e => setCity(e.target.value)}><option value="">All assigned cities</option>{data.territories.map(t => <option key={t.market_id} value={t.market_id}>{t.markets.name}</option>)}</select></label><button className={buttonClass} onClick={() => window.print()}>Print manifest</button></div><p className="text-sm text-neutral-500">Remaining stops only. City time zones apply. {date || "All dates"} · {stops.length} stops.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Stop / order", "Date / time", "Customer", "Address / instructions", "Driver"].map(h => <th key={h} className="p-3 border-b border-neutral-200">{h}</th>)}</tr></thead><tbody>{stops.map(s => <tr key={s.order.booking_id + s.kind} className="align-top"><td className="p-3 border-b border-neutral-200"><b className="capitalize">{s.kind}</b><br /><button className="text-teal-700 underline" onClick={() => openOrder(s.order.booking_id)}>{s.order.bookings.booking_ref}</button><br />{s.order.bookings.products?.name} × {s.order.bookings.quantity}</td><td className="p-3 border-b border-neutral-200">{s.date}<br />{stopTime(s)}<br />{s.market?.name}<br /><span className="text-xs">{s.market?.timezone}</span></td><td className="p-3 border-b border-neutral-200">{s.order.bookings.customer_name}<br />{s.order.bookings.customer_phone}</td><td className="p-3 border-b border-neutral-200 whitespace-pre-wrap">{s.kind === "delivery" ? s.order.bookings.delivery_address : s.order.bookings.collection_address || s.order.bookings.delivery_address}<br />{s.kind === "delivery" ? s.order.bookings.delivery_notes : s.order.bookings.collection_notes}</td><td className="p-3 border-b border-neutral-200">{s.driver?.name || "Unassigned / self"}<br />{s.driver?.phone}<br />{s.driver?.vehicle}</td></tr>)}</tbody></table></div>{!stops.length && <p>No remaining stops match these filters.</p>}</Panel></div>;
}
export function AgentDrivers({ data, busy, save }: { data: Workspace; busy: boolean; save: (body: Record<string, unknown>) => Promise<boolean> }) {
  return <div className="space-y-5"><Panel title="Add a driver"><p className="text-sm text-neutral-500">Drivers are contacts for your operations and do not receive workspace logins.</p><form className="grid gap-4 sm:grid-cols-2" onSubmit={async e => { const form = e.currentTarget, values = formValues(e); if (await save({ ...values, action: "driver" })) form.reset(); }}><Field name="name" label="Driver name" /><Field name="phone" label="Phone" type="tel" maxLength={50} /><Field name="vehicle" label="Vehicle / registration (optional)" required={false} /><button className={buttonClass} disabled={busy}>Add driver</button></form></Panel>{data.drivers.map(d => <Panel title={d.name} key={d.id}><form className="grid gap-4 sm:grid-cols-2" onSubmit={e => { const values = formValues(e); void save({ ...values, action: "driver", id: d.id, is_active: values.is_active === "on" }); }}><Field name="name" label="Name" value={d.name} /><Field name="phone" label="Phone" value={d.phone} type="tel" maxLength={50} /><Field name="vehicle" label="Vehicle" value={d.vehicle} required={false} /><label className="flex items-center gap-3"><input name="is_active" type="checkbox" defaultChecked={d.is_active} />Active driver</label><button disabled={busy} className={buttonClass}>Save driver</button></form></Panel>)}</div>;
}
export function AgentSupport() {
  return <Panel title="Working with Rentandroll">{[
    ["How do I receive orders?", "The admin assigns paid orders in your approved cities. Review the rental dates, then accept or decline. Customer details are available after acceptance."],
    ["What if I cannot fulfill an accepted order?", "Record the issue in the order's internal note and contact Rentandroll. The admin can reassign it. Do not leave a customer without an agreed handover."],
    ["How do unavailable dates work?", "Use Calendar to block dates across your assigned cities. Open overlapping orders must be declined or reassigned first. Both the first and last day are included."],
    ["Can I change prices, refunds or payment terms?", "Rentandroll manages customer pricing, payments and refunds. Agent compensation is agreed separately with the admin; customer rental totals are not agent earnings."],
    ["How do I contact a customer?", "Use Messages to send an email with a secure reply link. Replies are shown in your inbox. The workspace refreshes automatically every minute while visible; Refresh checks immediately."],
  ].map(([question, answer]) => <details key={question} className="border-t pt-4"><summary className="font-medium cursor-pointer">{question}</summary><p className="mt-3 text-neutral-600">{answer}</p></details>)}<a className="inline-block text-teal-700 underline" href="/contact">Contact Rentandroll support</a></Panel>;
}
