"use client";
import { useState } from "react";
import { Workspace, Area, buttonClass, formValues, inputClass } from "./shared";
import { isOpenStatus } from "@/lib/agent-workspace";
export default function AgentInbox({ data, busy, send, markRead, openOrder }: { data: Workspace; busy: boolean; send: (body: Record<string, unknown>) => Promise<boolean>; markRead: (ids: string[]) => Promise<boolean>; openOrder: (id: string) => void }) {
  const [selected, setSelected] = useState(""), [search, setSearch] = useState("");
  const threads = data.orders.filter(o => o.status === "accepted" && `${o.bookings.booking_ref} ${o.bookings.customer_name}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => {
    const last = (id: string) => data.messages.find(m => m.booking_id === id)?.created_at || "";
    return last(b.booking_id).localeCompare(last(a.booking_id));
  });
  const order = data.orders.find(o => o.booking_id === selected && o.status === "accepted");
  const messages = data.messages.filter(m => m.booking_id === selected).slice().reverse();
  const unread = messages.filter(m => m.direction === "customer" && !m.read_at);
  return <div className="grid lg:grid-cols-[290px_1fr] rounded-2xl border border-neutral-200 bg-white overflow-hidden min-h-[500px]">
    <aside className="border-b lg:border-r lg:border-b-0 p-4 space-y-3"><label className="block"><span className="sr-only">Search conversations</span><input className={inputClass} value={search} onChange={e => setSearch(e.target.value)} placeholder="Find a customer or order" /></label><div className="max-h-80 lg:max-h-[650px] overflow-y-auto">{threads.map(o => {
      const unreadCount = data.messages.filter(m => m.booking_id === o.booking_id && m.direction === "customer" && !m.read_at).length;
      return <button key={o.booking_id} disabled={busy} aria-pressed={selected === o.booking_id} className={`block w-full text-left rounded-xl p-3 mb-2 ${selected === o.booking_id ? "bg-teal-50 border border-teal-300" : "hover:bg-neutral-50 border border-transparent"}`} onClick={() => { setSelected(o.booking_id); const ids = data.messages.filter(m => m.booking_id === o.booking_id && m.direction === "customer" && !m.read_at).map(m => m.id); if (ids.length) void markRead(ids); }}><span className="font-medium">{o.bookings.customer_name || "Customer"}</span>{unreadCount > 0 && <span className="ml-2 bg-teal-700 text-white text-xs rounded-full px-2 py-0.5">{unreadCount} new</span>}<span className="block text-sm text-neutral-500">{o.bookings.booking_ref}</span><span className="block text-xs text-neutral-500 mt-1 truncate">{data.messages.find(m => m.booking_id === o.booking_id)?.body || "Start a conversation"}</span></button>;
    })}{!threads.length && <p className="text-sm text-neutral-500 p-3">Conversations become available after you accept an order.</p>}</div></aside>
    <section className="p-5 space-y-4 min-w-0">{!order ? <div className="py-16 text-center"><h2 className="text-xl font-semibold">Customer messages</h2><p className="text-neutral-500 mt-3">Select an order to coordinate delivery or collection.</p></div> : <><header className="flex justify-between gap-3 border-b border-neutral-200 border-neutral-200 pb-4"><div><h2 className="font-semibold text-xl">{order.bookings.customer_name}</h2><p className="text-sm text-neutral-500">{order.bookings.booking_ref} · {order.bookings.products?.name}</p></div><button className="text-teal-700 underline text-sm" onClick={() => openOrder(selected)}>View order</button></header><div className="max-h-[450px] overflow-y-auto space-y-3">{messages.map(m => <article key={m.id} className={`rounded-xl p-4 ${m.direction === "customer" ? "bg-teal-50 mr-4" : "bg-neutral-100 ml-4"}`}><p className="text-xs font-medium text-neutral-600">{m.direction === "customer" ? "Customer" : "You"} · {new Date(m.created_at).toLocaleString()} · {m.status}</p><p className="whitespace-pre-wrap break-words mt-2">{m.body}</p>{isOpenStatus(order.bookings.status) && m.direction === "agent" && ["failed", "queued"].includes(m.status) && <button className="underline text-teal-700 mt-2" disabled={busy} onClick={() => void send({ bookingId: selected, action: "message", messageId: m.id, body: m.body })}>Retry email</button>}</article>)}</div>{unread.length > 0 && <button disabled={busy} className="underline text-teal-700 text-sm" onClick={() => void markRead(unread.map(m => m.id))}>Mark new replies as read</button>}{isOpenStatus(order.bookings.status) ? <form key={selected} className="space-y-3" onSubmit={async e => { const form = e.currentTarget, values = formValues(e); if (await send({ action: "message", bookingId: selected, messageId: crypto.randomUUID(), body: values.body })) form.reset(); }}><Area name="body" label="Message to customer" required /><p className="text-xs text-neutral-500">Sends to the booking email with a private reply link. Internal operational notes belong in the order.</p><button className={buttonClass} disabled={busy}>Send message</button></form> : <p className="text-sm text-neutral-500">This order is closed. Its conversation is available for reference.</p>}</>}</section>
  </div>;
}
