export const bundleRequestCopy = {
  en: { invalid: "Invalid request", missing: "Kit not found", contact: "Add your name and a valid email address", dates: "Choose a valid start and end date", area: "Add your accommodation area", consent: "Confirm that we may use these details to manage your request", selection: "Choose at least one kit item", unavailable: "Kit requests are being configured. Please contact us on WhatsApp.", save: "Could not save your request", availability: "Could not check kit availability" },
  es: { invalid: "Solicitud no válida", missing: "Kit no encontrado", contact: "Añade tu nombre y un correo electrónico válido", dates: "Elige fechas de inicio y fin válidas", area: "Añade la zona de tu alojamiento", consent: "Confirma que podemos utilizar estos datos para gestionar tu solicitud", selection: "Elige al menos un artículo del kit", unavailable: "Estamos configurando las solicitudes de kits. Escríbenos por WhatsApp.", save: "No se pudo guardar tu solicitud", availability: "No se pudo comprobar la disponibilidad del kit" },
  de: { invalid: "Ungültige Anfrage", missing: "Paket nicht gefunden", contact: "Gib deinen Namen und eine gültige E-Mail-Adresse ein.", dates: "Wähle einen gültigen Mietbeginn und ein späteres Mietende.", area: "Gib die Lage deiner Unterkunft an.", consent: "Bestätige, dass wir deine Angaben zur Bearbeitung der Anfrage verwenden dürfen.", selection: "Wähle mindestens einen Artikel aus dem Paket.", unavailable: "Paketanfragen sind momentan nicht verfügbar. Bitte kontaktiere uns.", save: "Deine Anfrage konnte nicht gespeichert werden.", availability: "Die Verfügbarkeit des Pakets konnte nicht geprüft werden." },
} as const;

export const bundleAvailabilityNotes = {
  en: { unavailable: "No online stock is currently available for these dates.", manual: "This selection needs staff confirmation.", alternatives: "This kit component is selected from available alternatives by staff." },
  es: { unavailable: "No hay existencias disponibles en línea para estas fechas.", manual: "Esta selección necesita confirmación de nuestro equipo.", alternatives: "Nuestro equipo elige este componente del kit entre las alternativas disponibles." },
  de: { unavailable: "Für diese Termine ist online derzeit kein Bestand verfügbar.", manual: "Unser Team muss diese Auswahl noch bestätigen.", alternatives: "Unser Team wählt diesen Bestandteil des Pakets aus den verfügbaren Alternativen aus." },
} as const;
