import { localeRegistry, type Locale } from "./config";

export const quoteCopy = {
  en: { load: "Could not load this quote", reserve: "Could not reserve the quoted rental", payment: "Could not open secure payment", loading: "Loading your private quote…", unavailable: "Quote unavailable", invalid: "This private quote link is invalid or no longer available.", contact: "Contact us", pickup: "Customer pickup", both: "Delivery and collection", delivery: "Delivery", collection: "Collection", badge: "Private custom quote", confirmed: "Your rental is confirmed", title: "Your Valencia rental arrangement", intro: "We prepared this quote specifically for your dates and requirements.", rental: "Your rental", arrangement: "Arrangement", price: "Agreed price", total: "Total", conditions: "Included conditions", received: "Payment received. Your booking confirmation has been sent by email.", details: "Confirm your booking details", name: "Full name", email: "Email", phone: "Phone or WhatsApp", deliveryAddress: "Delivery address", collectionAddress: "Collection address", addressPlaceholder: "Start typing an address or place", collectionPlaceholder: "Start typing a collection address", reserving: "Reserving your dates…", continue: "Continue to secure payment", expiry: "Availability is confirmed when you continue. Your payment is handled securely by Stripe. Quote valid until", closed: "Please contact us if you would like an updated arrangement.", expired: "This quote has expired.", cancelled: "This quote has been cancelled." },
  es: { load: "No se pudo cargar este presupuesto", reserve: "No se pudo reservar el alquiler presupuestado", payment: "No se pudo abrir el pago seguro", loading: "Cargando tu presupuesto privado…", unavailable: "Presupuesto no disponible", invalid: "Este enlace privado no es válido o ya no está disponible.", contact: "Contacta con nosotros", pickup: "Recogida por el cliente", both: "Entrega y recogida", delivery: "Entrega", collection: "Recogida", badge: "Presupuesto privado personalizado", confirmed: "Tu alquiler está confirmado", title: "Tu alquiler en Valencia", intro: "Hemos preparado este presupuesto para tus fechas y necesidades.", rental: "Tu alquiler", arrangement: "Modalidad", price: "Precio acordado", total: "Total", conditions: "Condiciones incluidas", received: "Pago recibido. Te hemos enviado la confirmación de la reserva por correo electrónico.", details: "Confirma los datos de tu reserva", name: "Nombre completo", email: "Correo electrónico", phone: "Teléfono o WhatsApp", deliveryAddress: "Dirección de entrega", collectionAddress: "Dirección de recogida", addressPlaceholder: "Empieza a escribir una dirección o lugar", collectionPlaceholder: "Empieza a escribir una dirección de recogida", reserving: "Reservando tus fechas…", continue: "Continuar al pago seguro", expiry: "La disponibilidad se confirma al continuar. Stripe gestiona el pago de forma segura. Presupuesto válido hasta", closed: "Contacta con nosotros si quieres un presupuesto actualizado.", expired: "Este presupuesto ha caducado.", cancelled: "Este presupuesto se ha cancelado." },
  de: { load: "Dein Angebot konnte nicht geladen werden.", reserve: "Die angebotenen Mietartikel konnten nicht reserviert werden.", payment: "Die sichere Zahlung konnte nicht geöffnet werden.", loading: "Dein privates Angebot wird geladen …", unavailable: "Angebot nicht verfügbar", invalid: "Dieser private Angebotslink ist ungültig oder nicht mehr verfügbar.", contact: "Kontakt aufnehmen", pickup: "Selbstabholung", both: "Lieferung und Abholung", delivery: "Lieferung", collection: "Abholung", badge: "Dein individuelles Angebot", confirmed: "Deine Miete ist bestätigt", title: "Deine Miete in Valencia", intro: "Wir haben dieses Angebot für deine Termine und Anforderungen zusammengestellt.", rental: "Deine Mietartikel", arrangement: "Übergabe", price: "Vereinbarter Preis", total: "Gesamtbetrag", conditions: "Enthaltene Bedingungen", received: "Zahlung erhalten. Deine Buchungsbestätigung wurde per E-Mail versendet.", details: "Bestätige deine Buchungsdaten", name: "Vollständiger Name", email: "E-Mail-Adresse", phone: "Telefon oder WhatsApp", deliveryAddress: "Lieferadresse", collectionAddress: "Abholadresse", addressPlaceholder: "Adresse oder Ort eingeben", collectionPlaceholder: "Abholadresse eingeben", reserving: "Deine Termine werden reserviert …", continue: "Weiter zur sicheren Zahlung", expiry: "Die Verfügbarkeit wird beim Fortfahren bestätigt. Stripe wickelt deine Zahlung sicher ab. Das Angebot gilt bis", closed: "Kontaktiere uns, wenn du ein aktualisiertes Angebot möchtest.", expired: "Dieses Angebot ist abgelaufen.", cancelled: "Dieses Angebot wurde storniert." },
} as const;

export const amendmentCopy = {
  en: { load: "Could not load this transport quote", payment: "Could not open payment", loading: "Loading transport quote…", unavailable: "Transport quote unavailable", invalid: "This private link is invalid or no longer available.", contact: "Contact us", booking: "Booking", confirmed: "Transport service confirmed", title: "Add transport to your booking", updated: "Your booking has been updated. We will confirm the exact operational timing separately.", intro: "This is the transport quote prepared for your existing rental.", greeting: "Hi", rental: "Rental", service: "New service", both: "Delivery and collection", deliveryOnly: "Delivery only", custom: "Custom distance quote", delivery: "Delivery", collection: "Collection", note: "Note", total: "Total to pay", received: "Payment received and booking updated.", confirming: "Payment is being confirmed. This page will update automatically.", opening: "Opening secure payment…", pay: "Pay securely", expiry: "Quote valid until", stripe: "Payment is handled by Stripe.", closed: "Contact us if you still need transport.", expired: "This quote has expired.", cancelled: "This quote has been cancelled.", pendingDate: "To be confirmed", product: "Rental equipment", notPayable: "This transport quote is no longer payable", bookingClosed: "This booking can no longer be changed online", save: "Could not save the payment session", notConfigured: "Payment service is not configured", notFound: "Transport quote not found" },
  es: { load: "No se pudo cargar este presupuesto de transporte", payment: "No se pudo abrir el pago", loading: "Cargando presupuesto de transporte…", unavailable: "Presupuesto de transporte no disponible", invalid: "Este enlace privado no es válido o ya no está disponible.", contact: "Contacta con nosotros", booking: "Reserva", confirmed: "Transporte confirmado", title: "Añade transporte a tu reserva", updated: "Tu reserva se ha actualizado. Confirmaremos el horario exacto por separado.", intro: "Este es el presupuesto de transporte para tu alquiler actual.", greeting: "Hola", rental: "Alquiler", service: "Nuevo servicio", both: "Entrega y recogida", deliveryOnly: "Solo entrega", custom: "Presupuesto de distancia personalizado", delivery: "Entrega", collection: "Recogida", note: "Nota", total: "Total a pagar", received: "Pago recibido y reserva actualizada.", confirming: "Estamos confirmando el pago. Esta página se actualizará automáticamente.", opening: "Abriendo el pago seguro…", pay: "Pagar de forma segura", expiry: "Presupuesto válido hasta", stripe: "Stripe gestiona el pago.", closed: "Contacta con nosotros si todavía necesitas transporte.", expired: "Este presupuesto ha caducado.", cancelled: "Este presupuesto se ha cancelado.", pendingDate: "Por confirmar", product: "Artículos de alquiler", notPayable: "Este presupuesto de transporte ya no admite pagos", bookingClosed: "Esta reserva ya no puede modificarse en línea", save: "No se pudo guardar la sesión de pago", notConfigured: "El servicio de pago no está configurado", notFound: "Presupuesto de transporte no encontrado" },
  de: { load: "Das Transportangebot konnte nicht geladen werden.", payment: "Die Zahlung konnte nicht geöffnet werden.", loading: "Transportangebot wird geladen …", unavailable: "Transportangebot nicht verfügbar", invalid: "Dieser private Link ist ungültig oder nicht mehr verfügbar.", contact: "Kontakt aufnehmen", booking: "Buchung", confirmed: "Transport bestätigt", title: "Transport zu deiner Buchung hinzufügen", updated: "Deine Buchung wurde aktualisiert. Die genauen Zeiten bestätigen wir gesondert.", intro: "Hier findest du das Transportangebot für deine bestehende Miete.", greeting: "Hallo", rental: "Miete", service: "Zusätzlicher Service", both: "Lieferung und Abholung", deliveryOnly: "Nur Lieferung", custom: "Individuelles Entfernungsangebot", delivery: "Lieferung", collection: "Abholung", note: "Hinweis", total: "Zu zahlender Gesamtbetrag", received: "Zahlung erhalten und Buchung aktualisiert.", confirming: "Deine Zahlung wird bestätigt. Diese Seite aktualisiert sich automatisch.", opening: "Sichere Zahlung wird geöffnet …", pay: "Sicher bezahlen", expiry: "Angebot gültig bis", stripe: "Stripe wickelt die Zahlung ab.", closed: "Kontaktiere uns, wenn du weiterhin Transport benötigst.", expired: "Dieses Angebot ist abgelaufen.", cancelled: "Dieses Angebot wurde storniert.", pendingDate: "Noch zu bestätigen", product: "Mietartikel", notPayable: "Dieses Transportangebot kann nicht mehr bezahlt werden.", bookingClosed: "Diese Buchung kann nicht mehr online geändert werden.", save: "Der Zahlungsvorgang konnte nicht gespeichert werden.", notConfigured: "Der Zahlungsdienst ist nicht eingerichtet.", notFound: "Transportangebot nicht gefunden" },
} as const;

export function quoteMoney(cents: number, currency: string, locale: Locale) {
  return new Intl.NumberFormat(localeRegistry[locale].format, { style: "currency", currency: currency.toUpperCase() }).format(cents / 100);
}
export function quoteDate(value: string | null, locale: Locale, timezone = "Europe/Madrid") {
  if (!value) return amendmentCopy[locale].pendingDate;
  return new Intl.DateTimeFormat(localeRegistry[locale].format, { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(value));
}
