"use client";
import { useEffect, useMemo, useState } from "react";
type Product={id:string;name:string;is_active:boolean};
type Unit={id:string;asset_code:string;status:string;condition:string;location?:string|null;notes?:string|null;last_inspected_at?:string|null;products:{name:string}};
const statuses=["available","reserved","rented","maintenance","damaged","retired"];
const conditions=["new","good","fair","poor"];
export default function InventoryPage(){
 const [units,setUnits]=useState<Unit[]>([]),[products,setProducts]=useState<Product[]>([]),[error,setError]=useState(""),[productId,setProductId]=useState(""),[assetCode,setAssetCode]=useState(""),[filter,setFilter]=useState("all");
 useEffect(()=>{let active=true;fetch("/api/admin/inventory").then(async response=>({response,data:await response.json()})).then(({response,data})=>{if(!active)return;if(!response.ok){setError(data.error||"Could not load inventory");return;}setUnits(data.units);setProducts(data.products);setError("");});return()=>{active=false;};},[]);
 const visible=useMemo(()=>filter==="all"?units:units.filter(unit=>unit.status===filter),[units,filter]);
 async function createUnit(){const response=await fetch("/api/admin/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId,assetCode})});const data=await response.json();if(!response.ok){setError(data.error||"Could not create unit");return;}setUnits(current=>[...current,data.unit].sort((a,b)=>a.asset_code.localeCompare(b.asset_code)));setAssetCode("");setError("");}
 async function updateUnit(unit:Unit,updates:Record<string,unknown>){const response=await fetch(`/api/admin/inventory/${unit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(updates)});const data=await response.json();if(!response.ok){setError(data.error||"Could not update unit");return;}setUnits(current=>current.map(item=>item.id===unit.id?data.unit:item));setError("");}
 return <div><h1 className="text-3xl font-bold text-white">Inventory units</h1><p className="mt-2 text-sm text-neutral-500">Track each physical item, its condition, location and operational status.</p>{error&&<div className="mt-5 rounded-lg border border-red-900 bg-red-950/40 p-3 text-sm text-red-300">{error}</div>}
 <section className="mt-6 rounded-xl border border-neutral-800 bg-neutral-900 p-5"><h2 className="font-semibold text-white">Register physical item</h2><div className="mt-3 grid gap-3 md:grid-cols-[1fr_220px_auto]"><select value={productId} onChange={e=>setProductId(e.target.value)} className="rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-white"><option value="">Select product</option>{products.map(product=><option key={product.id} value={product.id}>{product.name}{product.is_active?"":" (draft)"}</option>)}</select><input value={assetCode} onChange={e=>setAssetCode(e.target.value)} placeholder="Asset code, e.g. RA-ST-001" className="rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-white"/><button disabled={!productId||!assetCode.trim()} onClick={createUnit} className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Add unit</button></div></section>
 <div className="mt-6 flex flex-wrap gap-2">{["all",...statuses].map(status=><button key={status} onClick={()=>setFilter(status)} className={`rounded-full px-3 py-1.5 text-xs font-medium ${filter===status?"bg-teal-500/20 text-teal-300":"bg-neutral-900 text-neutral-400"}`}>{status} {status==="all"?units.length:units.filter(unit=>unit.status===status).length}</button>)}</div>
 <div className="mt-4 space-y-3">{visible.map(unit=><div key={unit.id} className="rounded-xl border border-neutral-800 bg-neutral-900 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="min-w-52"><p className="font-mono text-sm font-semibold text-teal-300">{unit.asset_code}</p><p className="text-sm text-white">{unit.products.name}</p><p className="text-xs text-neutral-500">{unit.last_inspected_at?`Inspected ${new Date(unit.last_inspected_at).toLocaleDateString()}`:"Inspection not recorded"}</p></div><select value={unit.status} onChange={e=>updateUnit(unit,{...unit,status:e.target.value})} className="rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-white">{statuses.map(status=><option key={status}>{status}</option>)}</select><select value={unit.condition} onChange={e=>updateUnit(unit,{...unit,condition:e.target.value})} className="rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-white">{conditions.map(condition=><option key={condition}>{condition}</option>)}</select><input defaultValue={unit.location||""} onBlur={e=>updateUnit(unit,{...unit,location:e.target.value})} placeholder="Location" className="rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-white"/><input defaultValue={unit.notes||""} onBlur={e=>updateUnit(unit,{...unit,notes:e.target.value})} placeholder="Notes" className="flex-1 rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-white"/><button onClick={()=>updateUnit(unit,{...unit,markInspected:true})} className="rounded-lg border border-neutral-700 px-3 py-2 text-xs text-neutral-300">Mark inspected</button></div></div>)}{!visible.length&&<div className="rounded-xl border border-neutral-800 bg-neutral-900 p-10 text-center text-neutral-500">No inventory units in this view.</div>}</div></div>;
}
