import type { CategoryContent } from "./category-content";

/** Draft category labels and editorial copy; inventory membership comes from the catalogue. */
export const germanCategories: Record<string, CategoryContent> = {
  "baby-gear": { title: "Babys und Kleinkinder", description: "Kinderwagen, Reisebetten, Kindersitze und Hochstühle für deinen Aufenthalt in Valencia.", emoji: "👶", editorialHeading: "Passend zu deinem Kind und deiner Unterkunft", editorialParagraphs: ["Prüfe die Alters- und Gewichtsgrenzen, Maße und mitgelieferten Teile des konkreten Mietartikels. Für Treppen, Aufzüge, Transfers und den Schlafplatz zählen die tatsächlichen Bedingungen vor Ort.", "Wähle deine Mietdaten und prüfe die angebotenen Übergabeoptionen. Wenn ein bestimmtes Zubehör oder der Aufbau wichtig ist, kläre das vor der Buchung."] },
  "kids-family": { title: "Kinder und Familie", description: "Mietartikel für gemeinsame Ausflüge und Aktivitäten in Valencia.", emoji: "🛴", editorialHeading: "Gemeinsam unterwegs", editorialParagraphs: ["Wähle Artikel, die zum Alter deiner Kinder und zur geplanten Aktivität passen. Beachte die Hinweise zu Aufsicht, Untergrund und Schutzkleidung auf der Produktseite."] },
  mobility: { title: "Mobilität und Barrierefreiheit", description: "Rollstühle, Elektromobile und Rollatoren für deinen Aufenthalt in Valencia.", emoji: "♿", editorialHeading: "Die passende Unterstützung auswählen", editorialParagraphs: ["Vergleiche zulässiges Körpergewicht, Maße, Bedienung und Transportmöglichkeiten. Prüfe auch Türen, Aufzüge, Bordsteine und die geplante Route.", "Ein Mietartikel passt nicht automatisch zu jedem Zugang oder jeder Person. Wenn du uns deine Anforderungen nennst, können wir die Möglichkeiten vor der Buchung gemeinsam klären."] },
  "remote-work": { title: "Arbeiten unterwegs", description: "Monitore, Schreibtische und Bürostühle für deinen Arbeitsplatz in Valencia.", emoji: "💻", editorialHeading: "Deinen Arbeitsplatz einrichten", editorialParagraphs: ["Prüfe Anschlüsse, enthaltene Kabel und die Maße deines Arbeitsplatzes. Für größere Artikel müssen Zugang und Aufstellung in deiner Unterkunft passen."] },
  "home-living": { title: "Komfort in deiner Unterkunft", description: "Kühlung, Luftqualität und praktische Mietartikel für deinen Aufenthalt in Valencia.", emoji: "🏠", editorialHeading: "Auf den Raum kommt es an", editorialParagraphs: ["Prüfe Platzbedarf, Stromversorgung und die Anforderungen des konkreten Geräts. Bei mobilen Klimageräten sind auch die Abluftführung und ein geeigneter Fensterauslass wichtig."] },
  "travel-outdoors": { title: "Strand und Outdoor", description: "Schatten, Kühlboxen und weitere Mietartikel für Ausflüge in und um Valencia.", emoji: "🏖️", editorialHeading: "Deinen Ausflug vorbereiten", editorialParagraphs: ["Achte bei Strand- und Outdoorartikeln auf Wettergrenzen, geeigneten Untergrund und Transportmaße. Prüfe für Malvarrosa, Patacona oder einen anderen Zielort, ob deine geplante Nutzung dort erlaubt und geeignet ist."] },
  "fitness-wellness": { title: "Sport und Wohlbefinden", description: "Mietartikel für Tennis, Padel und Training während deines Aufenthalts.", emoji: "🎾", editorialHeading: "Für deine Aktivität auswählen", editorialParagraphs: ["Prüfe benötigten Platz, Untergrund, enthaltenes Zubehör und die Nutzungsgrenzen. Wähle Artikel, die zu deiner Erfahrung und deiner geplanten Aktivität passen."] },
  "events-celebrations": { title: "Feiern und Veranstaltungen", description: "Pizzaöfen, Slush-Maschinen, Karaoke und Spiele für Treffen in Valencia.", emoji: "🎉", editorialHeading: "Dein Treffen planen", editorialParagraphs: ["Die Produktseiten zeigen, welche Teile enthalten sind und welche Anforderungen an Platz, Strom oder Brennstoff gelten. Kläre mit deiner Unterkunft oder dem Veranstaltungsort, ob die geplante Nutzung erlaubt ist.", "Die Miete umfasst die jeweils aufgeführten Artikel. Ein Koch, Gastgeber, Zutaten oder Brennstoff sind nur enthalten, wenn dies ausdrücklich angegeben ist."] },
};

export const germanSubcategories: Record<string, string> = {
  "local-rehearsal": "Lokales Testsortiment",
  strollers: "Kinderwagen", "sleep-nursery": "Schlafen und Kinderzimmer", "car-seats": "Kindersitze",
  feeding: "Essen und Trinken", wheelchairs: "Rollstühle", scooters: "Elektromobile", walkers: "Rollatoren",
  monitors: "Monitore", desks: "Schreibtische", chairs: "Stühle", "air-quality": "Luftqualität", beach: "Strandartikel",
};
