import { NextRequest, NextResponse } from "next/server";
import { stripe, isStripeConfigured } from "@/lib/stripe";

/**
 * GET /api/checkout/session?id=cs_xxx — Look up a completed Stripe session
 *
 * Used by the /booking/success page to display booking details.
 * Returns metadata from the Stripe session (not from Supabase, since the
 * webhook may not have fired yet at the time the success page loads).
 */
export async function GET(request: NextRequest) {
  if (!isStripeConfigured() || !stripe) {
    return NextResponse.json({ error: "Stripe not configured" }, { status: 503 });
  }

  const { searchParams } = new URL(request.url);
  const sessionId = searchParams.get("id");

  if (!sessionId) {
    return NextResponse.json({ error: "Missing session ID" }, { status: 400 });
  }

  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId);

    if (session.payment_status !== "paid") {
      return NextResponse.json({ error: "Payment not completed" }, { status: 402 });
    }

    const meta = session.metadata || {};

    // Format dates for display
    const startDate = meta.start_date
      ? new Date(meta.start_date).toLocaleDateString("en-GB", { day: "numeric", month: "short" })
      : "";
    const endDate = meta.end_date
      ? new Date(meta.end_date).toLocaleDateString("en-GB", { day: "numeric", month: "short" })
      : "";

    return NextResponse.json({
      booking: {
        bookingRef: `Payment confirmed`, // Actual ref is generated by webhook — may not exist yet
        productName: meta.product_name || "Rental equipment",
        startDate,
        endDate,
        totalCents: session.amount_total || parseInt(meta.total_cents || "0"),
        customerEmail: session.customer_email || meta.customer_email || "",
      },
    });
  } catch (err) {
    console.error("[checkout/session] Error:", err);
    return NextResponse.json({ error: "Session not found" }, { status: 404 });
  }
}
